version: "3.3"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      AWS_ACCESS_KEY_ID: AKIASPXOW53KEPXAVPD3
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: us-east-2
      COGNITO_APP_CLIENT_ID: 5e728osp5d80kki1bhnh7ru9h0
      COGNITO_USER_POOL_ID: us-east-2_DVMVjSQFk
