version: "3.3"

services:
#  web:
#    build: .
#    ports:
#      - 8080:8080
#    depends_on:
#      - mongo
#    env_file:
#      - .env
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    env_file:
      - .env
    volumes:
      - ./database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASSWORD
      ME_CONFIG_BASICAUTH_USERNAME: $BA_USERNAME
      ME_CONFIG_BASICAUTH_PASSWORD: $BA_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$DB_USER:$DB_PASSWORD@mongo:27017/
